apiVersion: v1
kind: Service
metadata:
  name: golangapp-service
spec:
  selector:
    app: golangapp
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: golangapp
  labels:
    app: golangapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: golangapp
  template:
    metadata:
      labels:
        app: golangapp
    spec:
      containers:
      - name: golangapp
        image: kostov6/gowebapp:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5